# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Oracle Cloud에 ssh로 접속해서 scripts 실행시키기
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          GIT_USEREMAIL: ${{ secrets.GIT_USEREMAIL }}
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_PRIVATE_KEY }}
          envs: GIT_USERNAME,GIT_PASSWORD
          script: |
            cd ~/MV
            git config user.name $GIT_USERNAME
            git config user.email $GIT_USEREMAIL
            git checkout mz
            cp -rf ~/MZ/* ~/MV
            git add .
            git commit -m "pull files from the other repository"
            git push origin mz                        
